### ISSUE TITLE
My sprintfont-fix branch is still there

### ISSUE THREAD

**Issue by ZackCDLVI** [Afr0Games/Project-Dollhouse#151]
Might want to delete that branch or put it "up for grabs" because I'm not touching it or *this* repository's code anymore. I'm just watching from the side lines now.

**Comment by ksiazkowicz** [comment]
um, ok

**Comment by RHY3756547** [comment]
Didn't we already merge this? I think I was going to delete it anyways because of that, when I was doing a pass over the project management.

Speaking of which, we probably shouldn't have branches of our tagged releases, since source control contains backups by design, and the releases point to the relevant versions + source anyways.

**Comment by RHY3756547** [comment]
Done. However, since this already works fine for people with the font installed, I'm going to follow the wisdom of an old chinese proverb: "if it aint broke, dont fix it". Probably.

Glad to see you've reserved yourself to your own codebase until you're ready to commit here. Feel free to ask any questions about the engine.

**Comment by ZackCDLVI** [comment]
Sigh... Afr0 requested that spritefont fix be pushed to the master branch too (#135). It got reverted (259f57127c17bdf5a56698abe55f03b9a9eb831d) for an unknown reason. The branch was there to figure out why.
