### ISSUE TITLE
Divide project into smaller repos and use Git's submodules

### ISSUE THREAD

**Issue by ZackCDLVI** [Afr0Games/Project-Dollhouse#155]
![](http://i.imgur.com/zHufGwE.png)
![](http://i.imgur.com/hDpkoSx.png)
https://github.com/DigitalDollhouse/
https://github.com/DigitalDollhouse/DigitalDollhouse/wiki/Working-with-submodules
#ThisIsGonnaGetRejectCauseImARetard :D

**Comment by Afr0** [comment]
I don't know, man. I'm waiting this one out to see what Rhys has to say about it. Not sure I'm really seeing the point. He's gonna be pissed cos I didn't find the time to block you yet, though.
Anywhooo, I find it amusing that you've taken the time to write wiki-articles.
I'm gonna let you in on a little, dirty secret: the reason nobody wanted to join in on our project is not because we didn't write tutorials for n00bs or information on where to start; it's because nobody other than me, Rhys (and now Xezno, I guess), has sufficient interest in TSO *and* the skills to work on the project. We figured that one out a long time ago, that's why we never bothered with the stuff you're doing now.
Don't believe me? It's simple, I'll tell you why: GitHub isn't a place for n00bs. People learning to code aren't working on collaborative projects (certainly not on the magnitude that would require Github, anyway). They're not going to be learning to use Github at the same time. And by the time they feel confident enough to start working on collaborative projects, learning to use Github is going to be a breeze. If they're interested in working on a project, they will just ask, or submit pull requests.

Date: Thu, 25 Jun 2015 21:20:50 -0700

**Comment by LetsRaceBwoi** [comment]
>They're not going to be learning to use Github at the same time. 

I learned GitHub a year ago; I had knowledge then but until recently I had no clue about how to submit a pull request; this project, along with Zack's instructions, taught me.

**Comment by Afr0** [comment]
Exactly, that's what I said. 
If you're willing to put in the effort to learn project, you shouldn't need guidance on using Github, at least not on a per-project basis, because you'll go out and find the information on your own. 

Date: Fri, 26 Jun 2015 08:49:36 -0700

**Comment by ZackCDLVI** [comment]
You could be an experieced coder coming from Sourceforge.

**Comment by ZackCDLVI** [comment]
Back on topic, submodules was experiment that'll be used in New Sims 3. I just used PD as a test since it has the most complicated codebase that I'm familer with. From it I managed to strip down the main repo of only game with the server, Other and Patcher seperated. Everything except the patcher connects through Other.

**Comment by RHY3756547** [comment]
Who in the right mind would use sourceforge in its current state? The point is, we shouldn't have to tell people how to use pretty standard tools, because that information is readily available all across the internet. (usually one google search away)

As for using submodules for what appears to be literally fucking everything, it's probably not the greatest idea in the project's current state. We're still mostly a research project, so a ton of the systems are heavily coupled and have no reliable static "API" that things using them can rely on. Things can and will change incredibly quickly, having everything separate will just cause even more confusing github issues when people want to test with submodule branches that may be incompatible with the other submodules/the main project. Also... where else will these modules be used? Makes sense for something like dblinq that is used everywhere... but for some pretty specific parts of a TSO recreation, not so much.

So the answer is, not right now and probably not for a long time. Sorry.

---

Also - if you want us to take you seriously, you might be better off not including a snarky comment suggesting that we will ignore what you're saying because of some sort of vendetta. You might also want to stop trying and suggesting huge changes with no reasoning in the post.

**Comment by ZackCDLVI** [comment]
I closed the issue for you.

**Comment by RHY3756547** [comment]
Thanks, I guess? I was waiting for Afr0 to comment and considered leaving it open to consider when things are more stable, but I guess that would be too far in the future anyways to just leave this open.

**Comment by ZackCDLVI** [comment]
Clone the repos and test it out for yourselves.

**Comment by RHY3756547** [comment]
Don't have to tell us... It will be a while before we test it though, probably.

**Comment by ZackCDLVI** [comment]
You're on break, Rhys.

**Comment by RHY3756547** [comment]
???

**Comment by ZackCDLVI** [comment]
Well, you already spent that time arguing with me. At least this would be productive.

**Comment by LetsRaceBwoi** [comment]
*sigh*

**Comment by MuppetJohee** [comment]
Seriously Zack, you're making no more than nausea here right now, please just stop. Move on.

**Comment by KenBeanNet** [comment]
Yes.  My first comment. I logged in here just to say, everyone please just shut up with the arguing.

Thanks.

**Comment by ZackCDLVI** [comment]
Remove the labels, LetsRaceBwoi.

**Comment by ksiazkowicz** [comment]
Unsubscribing until @ZackCDLVI gets his act together or @Afr0 just blocks him.

I'm tired of getting all that drama streamed right into my GitHub feed/e-mail. To be honest, I don't even slightly give a crap about it.

**Comment by LetsRaceBwoi** [comment]
I'm going to lock this issue.  Remember that any of the contributors can still speak & unlock if they wish.  I've had enough of Zack's drama.
