### ISSUE TITLE
Additional prerequisites for Windows 10

### ISSUE THREAD

**Issue by ZackCDLVI** [Afr0Games/Project-Dollhouse#158]
When installing XNA Game Studio 4.0 on Windows 10, you'll need [Games for Windows Marketplace Client](http://www.xbox.com/en-US/LIVE/PC/DownloadClient) before installing it, otherwise it'll fail. I had to Google up this [workaround](http://blogs.msdn.com/b/astebner/archive/2014/11/06/10570404.aspx) to find out.

**Comment by LetsRaceBwoi** [comment]
How is this anything to do with the game? Surely you should just submit a pull request with changes to the README file; there's no need to open an issue.  _Edit the wiki or README files!_

**Comment by RHY3756547** [comment]
Windows 10 isn't a target for us to consider right now since it's a pre-release OS. Once we change the build process to the latest version of Visual Studio this won't be a problem, but we can't right now because I'm busy working on a huge branch and it's kind of a waste of time until windows 10 rolls around. 

Either way, I updated the readme with it because it took literally no time to.

I'm not quite sure why you can still post here either. (or what the hell your icon is...)

**Comment by ZackCDLVI** [comment]
> How is this anything to do with the game?

Because it's needed to compile the game. Specifically the content processor until PD switches to MonoGame's.

> Surely you should just submit a pull request with changes to the README file; there's no need to open an issue.

Last I made a README change, it boiled down to another argument.

> Windows 10 isn't a target for us to consider right now since it's a pre-release OS.

Windows 10 is rolling at the end of this month.

**Comment by RHY3756547** [comment]
> Windows 10 is rolling at the end of this month.
It'll be an issue then. It isn't now.

**Comment by LetsRaceBwoi** [comment]
Locking.
